const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      name: "Zapatos",
      price: 100,
      description: "Zapatos de cuero de la marca Nike",
      availability:"Disponible",
      amount: 100,


    },
    {
      id: 2,
      discount: 40,
      cover: "./images/flash/flash-2.png",
      name: "Reloj",
      price: 20,
      description: "Zapatos de cuero de la marca Nike",
      availability:"Disponible",
      amount: 100,
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/flash/flash-3.png",
      name: "Dispositivo Mobil",
      price: 200,
      description: "Zapatos de cuero de la marca Nike ",
      availability:"Disponible",
      amount: 100,
    },
    {
      id: 4,
      discount: 40,
      cover: "./images/flash/flash-4.png",
      name: "Smart Watch ",
      price: 900.000,
      description: "Zapatos de cuero de la marca Nike",
      availability:"Disponible",
      amount: 100,
    },
    {
      id: 5,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      name: "Zapatos",
      price: 90.000,
      description: "Zapatos de cuero de la marca Nike",
      availability:"Disponible",
      amount: 100,
    },
    {
      id: 6,
      discount: 50,
      cover: "./images/flash/flash-3.png",
      name: "Zapatos",
      price: 100.000,
      description: "Zapatos de cuero de la marca Nike",
      availability:"Disponible",
      amount: 100,
    },
  ],
}
export default Data
